sudo: required

services:
  - docker

language: go
go:
  - "1.13"

before_install:
  - go get github.com/karalabe/xgo

install: go get -d ./...

script: make travisbuild

deploy:
  provider: releases
  api_key:
    secure: "Vdt2PPWBjrbJ0eYjr86YPLpl+ghYoFFRxw8GH0Khcy7Ab3oeMUMY5jcDD+xrSv6F9QQ6oPpXeXctCl6Ro2rEcuEtA2DI70BjtYOc2vUJGSxrI35fkbrQzJ7J4KLLgHCfJbSbn2ncJpu5rsZVGmTasKlnQlshDASHgrzpWLbUGcQVUGSO2oaNbQq/fiHAHVDdvm84I5TyZVUkX59GpyDfkbEycaBiBA7Avqsgm5m4EsUqSK71WFkOzCWpXgIFcBQRMxqxT9QCQ8ExqcT7d8jDLZTyJIfbilInnle6SUCOGRJ4bf0zIJ3XRokYxUfgThhtZLpDCtveB2jbt6poXcQXVzN82CKbyt62q0QC2pN3vH2//pEQSfA0NSHT4/qGQH+CKd3licK4USgesEUNoLJCulrQru0Ir5RLkFq0mv+C6RS3qLBXLyFiQYumsXUbgA5J3k/9VVOsE9NHLJTvDp8Hkx/4G7vivSKhIm8zAi6szfF+iB8AD9yR9l4X/Ciiay1NymPMqXcbbVCCrrXXgQYWtdMCT55dVoXhYkMMVw3Y0r6VsXfvUmHc2e7APlOrClmLI6XfVhK71fQ18mwRt7Qvqx1ljXUDQQHi4+m6WxifP8CN1eZV0Kl8ccv/YhR6p5KRUwhfxs+8lewTF33gs6WocaIqFRi/3H1EufFY92ptpds="
  file_glob: true
  file:
    - "build/tun2socks*"
  skip_cleanup: true
  on:
    tags: true
